config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    # staic pages
    root           to: 'static_pages#home'
    get '/mypage', to: 'static_pages#mypage'

    # devise
    devise_for :users

    # goods
    resources :goods, only: [:index, :show]

    # payments
    resources :payments, only: [:show, :create]

    # pay codes
    resources :pay_codes, only:[:new, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :payments
end

app/models/pay_code.rb
class PayCode < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :good

  def sum
    if !self.good.nil? && !self.good.price.nil? || !self.number
      return self.good.price * self.number
    else
      return false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  has_many :payments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def after_sign_in_path_for(resource)
    mypage_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def set_locale
    I18n.locale = locale
  end

  def locale
    @locale ||= params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    if I18n.locale == I18n.default_locale
      options.merge(locale: '')
    else
      options.merge(locale: I18n.locale)
    end
  end

  protected

  def configure_permitted_parameters
    added_attrs = [ :name, :email, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up,        keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def index
    @goods = Good.all
  end

  def show
    @good ||= Good.find_by(id: params[:id])
    if @good.nil?
      return redirect_to(goods_path, alert: "この商品は存在しません")
    end
    @payment = Payment.new
    value = current_user.money / @good.price
    @max = value < @good.number ? value : @good.number
  end
end

app/controllers/pay_codes_controller.rb
class PayCodesController < ApplicationController
  def new
    @pay_code = PayCode.new
  end

  def create
    @pay_code ||= PayCode.find_by(key: params[:pay_code][:key].upcase)
    if @pay_code.nil?
      flash.now[:alert] = "このコードは存在しません"
      @pay_code = PayCode.new(key: params[:pay_code][:key])
      render 'pay_codes/new'
    else
      current_user.update_attribute(:money, current_user.money + @pay_code.price)
      @pay_code.destroy
      flash[:notice] = "入金を完了しました"
      redirect_to mypage_path
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    @payment = Payment.new(permit_payment)

    @good ||= Good.find_by(id: @payment.good_id)
    if @good.nil?
      return redirect_to(goods_path, alert: "この商品は存在しません")
    end

    value = 0

    if @payment.sum
      value = current_user.money - @payment.sum
      if value < 0
        flash.now[:alert] = "いまの所持金では、この商品を購入できません"
        return render("/goods/show")
      end
    end

    if @payment.save
      current_user.update_attribute(:money, value)
      value = @good.number - @payment.number
      @good.update_attribute(:number, value)
      redirect_to @payment, notice: "商品を購入しました"
    else
      render "/goods/show"
    end
  end

  def show
    @payment ||= Payment.find_by(id: params[:id])
    if @payment.nil? || @payment.user_id != current_user.id
      return redirect_to(mypage_path, alert: "この商品明細は存在しません")
    end
  end

  private

  def permit_payment
    params[:payment][:user_id] = current_user.id

    params.require(:payment).permit(
      :number, :user_id, :good_id
    )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def mypage
    @user = current_user
    @payments = @user.payments.order("id DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # alert => danger, notice => success
  def alert_class(message_type)
    case message_type
      when "alert"
        return "danger"
      when "notice"
        return "success"
      else
        return message_type
    end
  end

  def default_link_nav(str, path)
    return link_to(str, path, class: "nav-item nav-link")
  end

  def logout_link_nav(str, path, text)
    return link_to(str, path, method: "delete", data: { confirm: text }, class: "nav-item nav-link") 
  end

  def costom_devise_error_messages
    return "" if resource.errors.empty?
    html = ""
    messages = resource.errors.full_messages.each do |msg|
      html += <<-EOF
      <div class="alert alert-danger">#{msg}</div>
      EOF
    end
    html.html_safe
  end

  def locale_url_for(locale, str)
    if locale == I18n.default_locale.to_s
      link_to_if(
        params[:locale].present? && params[:locale] != locale, str,
        url_for(
          controller: controller.controller_name,
          action: controller.action_name,
          locale: ''
        )
      )
    else
      link_to_if(
        params[:locale] != locale, str,
        url_for(
          controller: controller.controller_name,
          action: controller.action_name,
          locale: locale
        )
      )
    end
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/pay_codes_helper.rb
module PayCodesHelper
end

app/helpers/smart_label_form_builder.rb
# coding: utf-8
class SmartLabelFormBuilder < ActionView::Helpers::FormBuilder
  def label(method, content_or_options_with_block = nil, options = {}, &block)
    if !block_given?
      super(method, content_or_options_with_block, options)
    else
      options = content_or_options_with_block.is_a?(Hash) ? content_or_options_with_block.stringify_keys : {}
      @template.content_tag(:label, options, &block)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/goods/_good.html.erb
<%= render 'goods/good_info', object: good %>

app/views/goods/_good_info.html.erb
<div class="col-md-6">
  <div class="alert alert-secondary">
    <h4 class="alert-heading">
      <%= object.name %>
      <% if controller.action_name == "index" %>
        <%= link_to t(".show_link"), object, class: "float-right btn btn-primary btn-sm" %>
      <% end %>
    </h4>
    <hr>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <td scope="row" class="pt-0 pb-0" style="width: 50%;"> Product value</td>
          <td class="pt-0 pb-0" style="width: 50%;"><%= object.price %> yen</td>
        </tr>
        <tr>
          <td scope="row" class="pt-0 pb-0">Stock</td>
          <td class="pt-0 pb-0"><%= object.number %> pieces</td>
        </tr>
      </tbody>
    </table>
    <% if controller.action_name == "show" %>
      <hr>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td scope="row" class="pt-0 pb-0" style="width: 50%;"><%= User.human_attribute_name(:money) %></td>
            <td class="pt-0 pb-0" style="width: 50%;"><%= current_user.money %> yen</td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/goods/index.html.erb
<h2><%= t(".title") %></h2>

<div class="row">
  <%= render @goods %>
</div>

app/views/goods/show.html.erb
<h2><%= t(".title") %></h2>

<div class="row">
  <%= render 'goods/good_info', object: @good %>
</div>

<div class="row">
  <div class="col-md-6">
    <%= form_for @payment do |f| %>
      <%= render 'layouts/error_messages', object: @payment %>

      <%= f.hidden_field :good_id, value: @good.id %>

      <div class="form-group">
        <%= f.label :number do %>
          <%= Payment.human_attribute_name(:number) %> <%= t(".form.min_max", min: 1, max: @max) %>
        <% end %>
        <%= f.number_field :number, value: '', span: 1, min: 1, max: @max,
          placeholder: Payment.human_attribute_name(:number), class: "form-control", required: true %>
      </div>

      <%= f.submit t(".form.submit.link"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <% object.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'timedout' %>
    <% next %>
  <% end %>
  <div class="alert alert-<%= alert_class(message_type) %> alert-dismissible fade show" role="alert" id='alert-offline'>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<%# header %>
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <%= link_to t('header.logo'), root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav header-menu">
      <%= default_link_nav t('header.top_page'), root_path %>
      <% if user_signed_in? %>
        <%= default_link_nav t('header.mypage'),        mypage_path %>
        <%= default_link_nav t('header.goods'),         goods_path %>
        <%= default_link_nav t('header.pay_code'),      new_pay_code_path %>
        <%= logout_link_nav  t('header.sign_out.link'), destroy_user_session_path, t('header.sign_out.confirm') %>
      <% else %>
        <%= default_link_nav t('header.log_in'),        new_user_session_path %>
        <%= default_link_nav t('header.registration'),  new_user_registration_path %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_script.html.erb
<script>
  var url = window.location.pathname;
  $('.header-menu a[href="'+url+'"]').addClass('active');

  $('.field_with_errors input').addClass('is-invalid');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= t("head.title") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
      <hr>
      <p>
        <%= locale_url_for('ja', "日本語") %> | <%= locale_url_for('en', "English") %>
      </p>
    </div>
  </body>
  <%= render "layouts/script" %>
</html>

app/views/pay_codes/new.html.erb
<h2><%= t(".title") %></h2>

<%= form_for @pay_code do |f| %>
  <div class="form-group">
    <%= f.label :key do %>
      <%= PayCode.human_attribute_name(:key) %> <%= t(".form.length", length: 16) %>
    <% end %>
    <%= f.text_field :key, maxlength: 16, autocomplete: "off",
      placeholder: PayCode.human_attribute_name(:key), class: "form-control", required: true %>
  </div>

  <%= f.submit t(".form.submit"), class: "btn btn-primary" %>
<% end %>

app/views/payments/_payment.html.erb
<tr>
  <th scope="row">
    <%= payment.good.name %>
  </th>
  <td>
    <%= payment.number %>
  </td>
  <td>
    <%= payment.sum %>
  </td>
  <td>
    <%= link_to t(".show_link"), payment, class: "btn btn-sm btn-primary" %>
  </td>
</tr>

app/views/payments/show.html.erb
<h2><%= t(".title") %></h2>

<div class="row">
  <div class="col-md-6">
    <div class="alert alert-secondary">
      <h4 class="alert-heading">
        <%= @payment.good.name %>
      </h4>
      <hr>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td scope="row" class="pt-0 pb-0" style="width: 50%;"><%= t(".price") %></td>
            <td class="pt-0 pb-0" style="width: 50%;"><%= @payment.good.price %> yen</td>
          </tr>
          <tr>
            <td scope="row" class="pt-0 pb-0"><%= t(".number") %></td>
            <td class="pt-0 pb-0"><%= @payment.number %> pieces</td>
          </tr>
        </tbody>
      </table>
      <hr>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td scope="row" class="pt-0 pb-0" style="width: 50%;"><%= t(".total") %></td>
            <td class="pt-0 pb-0" style="width: 50%;"><%= @payment.sum %> yen</td>
          </tr>
        </tbody>
      </table>
      <hr>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td scope="row" class="pt-0 pb-0" style="width: 50%;"><%= t(".purchase_at") %></td>
            <td class="pt-0 pb-0" style="width: 50%;"><%= @payment.created_at %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t "static_pages.home.title" %></h1>
  <p class="lead"><%= t "static_pages.home.lend" %></p>
</div>

app/views/static_pages/mypage.html.erb
<h2>My page</h2>

<div class="alert alert-secondary">
  <h4 class="alert-heading">
    Account infomation
  </h4>
  <hr>
  <table class="table table-borderless">
    <tbody>
      <tr>
        <th scope="row" style="width: 35%;">Account name</th>
        <td style="width: 75%;"><%= current_user.name %></td>
      </tr>
      <tr>
        <th scope="row">Mail adress</th>
        <td><%= current_user.email %></td>
      </tr>
      <tr>
        <th scope="row">Possession money</th>
        <td><%= current_user.money %> yen</td>
      </tr>
    </tbody>
  </table>
</div>

<% if @payments.present? %>
  <div class="alert">
    <h4 class="alert-heading">
      Products purchase list
    </h4>
    <hr>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col" style="width: 50%;">Name</th>
          <th scope="col" style="width: 20%;">Count</th>
          <th scope="col" style="width: 20%;">Total</th>
          <th scope="col" style="width: 10%;"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @payments %>
      </tbody>
    </table>
  </div>
<% end %>